name:                parcopy
version:             0.1.2.0
github:              "IBM/parcopy"
license:             Apache-2.0
author:              "Shlomo Shuck"
maintainer:          "sjshuck@us.ibm.com"
copyright:           "2019-2020 IBM Corporation"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/IBM/parcopy#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- directory
- filepath
- lens
- mtl
- optparse-applicative
- resourcet
- unix
- unliftio
- unliftio-core

library:
  source-dirs: src

executables:
  parcp:
    main:                ParCp.hs
    source-dirs:         app
    ghc-options:
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is ParCp
    dependencies:
    - parcopy

  parrm:
    main:                ParRm.hs
    source-dirs:         app
    ghc-options:
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is ParRm
    dependencies:
    - parcopy

tests:
  parcopy-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - parcopy
